language: python
python:
  - "2.7"
  
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/CustomSettings
  - PLATFORMIO_CI_SRC=examples/DoorSensor
  - PLATFORMIO_CI_SRC=examples/HookToEvents
  - PLATFORMIO_CI_SRC=examples/IteadSonoff
  - PLATFORMIO_CI_SRC=examples/LedStrip
  - PLATFORMIO_CI_SRC=examples/LightOnOff
  - PLATFORMIO_CI_SRC=examples/TemperatureSensor
  - CPPLINT=true

install:
  - pip install -U platformio
  - pip install cpplint
  - platformio lib install 64  # ArduinoJson
  - platformio lib install 346  # AsyncMqttClient 
  - platformio lib install 1106  # Bounce2

script:
  - if [[ -z "$CPPLINT" ]]; then make test; else platformio ci --lib="." --board=esp01 --board=nodemcuv2; fi
  
