language: python
python:
  - "2.7"

env:
  - PLATFORMIO_CI_SRC=examples/CustomSettings
  - PLATFORMIO_CI_SRC=examples/DoorSensor
  - PLATFORMIO_CI_SRC=examples/HookToEvents
  - PLATFORMIO_CI_SRC=examples/IteadSonoff
  - PLATFORMIO_CI_SRC=examples/LightOnOff
  - PLATFORMIO_CI_SRC=examples/TemperatureSensor
  - PLATFORMIO_CI_SRC=examples/LedStrip
  - PLATFORMIO_CI_SRC=examples/Broadcast
  - PLATFORMIO_CI_SRC=examples/GlobalInputHandler
  - CPPLINT=true

install:
  - pip install -U platformio
  - pip install cpplint
  # install current build as a library with all dependencies
  - platformio lib -g install file://.

script:
  - if [[ "$CPPLINT" ]]; then make cpplint; else platformio ci --board=esp01 --board=nodemcuv2; fi
