site_name: Homie for ESP8266
repo_name: 'marvinroger/homie-esp8266'
repo_url: 'https://github.com/marvinroger/homie-esp8266'
edit_uri: edit/develop/docs

pages:
  - Welcome: index.md
  - Quickstart:
    - What is it?: quickstart/what-is-it.md
    - Getting started: quickstart/getting-started.md
  - Advanced usage:
    - Built-in LED: advanced-usage/built-in-led.md
    - Branding: advanced-usage/branding.md
    - Events: advanced-usage/events.md
    - Logging: advanced-usage/logging.md
    - Streaming operator: advanced-usage/streaming-operator.md
    - Input handlers: advanced-usage/input-handlers.md
    - Broadcast: advanced-usage/broadcast.md
    - Custom settings: advanced-usage/custom-settings.md
    - Resetting: advanced-usage/resetting.md
    - Standalone mode: advanced-usage/standalone-mode.md
    - Magic bytes: advanced-usage/magic-bytes.md
    - Range properties: advanced-usage/range-properties.md
    - Deep sleep: advanced-usage/deep-sleep.md
    - Miscellaneous: advanced-usage/miscellaneous.md
    - UI Bundle: advanced-usage/ui-bundle.md
  - Configuration:
    - JSON configuration file: configuration/json-configuration-file.md
    - HTTP JSON API: configuration/http-json-api.md
  - Others:
    - OTA/configuration updates: others/ota-configuration-updates.md
    - Homie implementation specifics: others/homie-implementation-specifics.md
    - Limitations and known issues: others/limitations-and-known-issues.md
    - Troubleshooting: others/troubleshooting.md
    - C++ API reference: others/cpp-api-reference.md
    - Upgrade guide from v1 to v2: others/upgrade-guide-from-v1-to-v2.md
    - Community projects: others/community-projects.md

theme: material
extra:
  logo: assets/logo.png
  palette:
    primary: red
    accent: red
  feature:
    tabs: true
  social:
    - type: cog
      link: http://setup.homie-esp8266.marvinroger.fr

markdown_extensions:
  - meta
  - footnotes
  - codehilite
  - admonition
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
